spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/bp_database
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Enable DEBUG logging for the Spring DispatcherServlet
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# Instruct Spring MVC to include detailed request logs (such as headers and parameters)
spring.mvc.log-request-details=true